// <auto-generated/> - StyleCop hack to not enforce enum value comments in this file.
namespace Fabric.Terminology.TestsBase
{
    internal static class TestTraits
    {
        public const string Category = "Category";
    }

    internal static class TestCategory
    {
        public const string LongRunning = "LongRunning";
    }
}
